In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
test_df = pd.read_csv('Data_for_UCI_named.csv', error_bad_lines= False)

test_df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [3]:
test_df = test_df.drop(columns = 'stab')

test_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  unstable  

[10000 rows x 13 columns]

In [4]:
test_df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stabf    0
dtype: int64

In [5]:
test_df.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [6]:
x = test_df.drop(columns = 'stabf')

y = test_df.stabf

display(x)
y

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  
1    -1.255012  0.413441  0.862414  0.562139  0.781760  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  
...        ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  

[10000 rows x 12 columns]

0       unstable
1         stable
2       unstable
3       unstable
4       unstable
          ...   
9995    unstable
9996      stable
9997      stable
9998    unstable
9999    unstable
Name: stabf, Length: 10000, dtype: object

In [7]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=1)

In [8]:
display(x_train)

x_test

tau1      tau2      tau3      tau4        p1        p2        p3  \
2694  6.255995  2.542401  7.024714  9.476518  3.529888 -1.224881 -0.688228   
5140  5.070581  5.490253  8.075688  0.761075  4.220888 -1.280596 -1.902185   
2568  1.220072  8.804028  3.874283  8.433949  3.614027 -1.039236 -0.953566   
3671  7.498402  6.697603  8.798626  2.126236  3.134585 -1.581906 -0.589386   
7427  7.074006  1.337511  6.100756  7.759156  2.526922 -0.922540 -0.632600   
...        ...       ...       ...       ...       ...       ...       ...   
2895  9.504984  5.265415  2.029617  8.026334  3.449756 -0.922754 -1.526305   
7813  8.035818  4.632548  1.177810  1.204950  4.093208 -1.568218 -0.819966   
905   7.052560  3.264057  1.405949  4.497549  3.741358 -0.629026 -1.407945   
5192  5.085242  1.790031  2.486392  2.848192  3.159670 -0.892898 -1.025461   
235   1.205354  6.995045  5.930860  2.523856  5.230127 -1.755047 -1.567927   

            p4        g1        g2        g3        g4  
2694 -1.616780  0.568221  0.618403  0.685739  0.660088  
5140 -1.038107  0.443515  0.097244  0.916955  0.129254  
2568 -1.621224  0.908353  0.923594  0.238881  0.660156  
3671 -0.963293  0.260826  0.899003  0.964752  0.600598  
7427 -0.971782  0.984580  0.716082  0.836928  0.165162  
...        ...       ...       ...       ...       ...  
2895 -1.000696  0.191864  0.611297  0.080008  0.350312  
7813 -1.705024  0.223384  0.317770  0.726623  0.441620  
905  -1.704387  0.868306  0.605566  0.100591  0.747320  
5192 -1.241311  0.473917  0.418512  0.326253  0.982488  
235  -1.907153  0.861961  0.202768  0.848373  0.739993  

[8000 rows x 12 columns]

tau1      tau2      tau3      tau4        p1        p2        p3  \
9953  6.877876  4.113820  9.356768  8.299753  4.056779 -1.897470 -1.590581   
3850  5.802841  6.271371  4.731540  3.819867  3.579569 -1.709480 -1.067511   
4962  2.286998  4.385142  2.830232  5.293880  3.035814 -1.202764 -0.902011   
3886  5.019920  2.209962  6.266080  0.578901  4.322584 -1.960207 -1.074561   
5437  7.646145  9.187896  5.484219  9.934313  3.634226 -1.254541 -1.335366   
...        ...       ...       ...       ...       ...       ...       ...   
3919  8.320531  3.394352  1.468729  8.766874  3.940123 -1.599081 -0.931023   
162   2.290102  3.028512  8.071234  6.169944  3.624592 -1.104003 -0.820951   
7903  7.848945  0.684889  0.728223  6.702948  2.599685 -0.563497 -1.210069   
2242  2.173967  5.776797  4.597638  6.399330  2.869349 -0.931891 -1.237955   
2745  1.467618  9.389085  6.019740  9.376247  4.242404 -1.894794 -1.589085   

            p4        g1        g2        g3        g4  
9953 -0.568728  0.276567  0.845536  0.112440  0.822562  
3850 -0.802579  0.077527  0.416478  0.912846  0.861306  
4962 -0.931039  0.924216  0.130186  0.703887  0.063811  
3886 -1.287815  0.546910  0.065992  0.427349  0.814648  
5437 -1.044319  0.561528  0.121611  0.787318  0.300314  
...        ...       ...       ...       ...       ...  
3919 -1.410020  0.657445  0.493384  0.178907  0.173240  
162  -1.699638  0.785595  0.770194  0.234290  0.225070  
7903 -0.826119  0.185122  0.559799  0.682418  0.886902  
2242 -0.699503  0.942680  0.743103  0.152161  0.305183  
2745 -0.758525  0.659519  0.273217  0.526145  0.851163  

[2000 rows x 12 columns]

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_transformed = scaler.fit_transform(x_train)

x_train_transformed = pd.DataFrame(x_train_transformed,columns = x_train.columns)

x_train_transformed

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1    -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2    -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3     0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4     0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.551314  0.007408 -1.177640  1.016898 -0.397177  0.759820 -0.636951   
7996  1.015925 -0.223483 -1.489381 -1.479078  0.451468 -0.731994  0.990355   
7997  0.657609 -0.722756 -1.405888 -0.274301 -0.012584  1.438694 -0.364266   
7998 -0.059316 -1.260532 -1.010471 -0.877808 -0.779769  0.828824  0.516923   
7999 -1.473214  0.638438  0.250122 -0.996484  1.950944 -1.163800 -0.732842   

            p4        g1        g2        g3        g4  
0    -0.845074  0.160918  0.339859  0.585568  0.492239  
1     0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2    -0.855302  1.399350  1.451534 -1.045743  0.492489  
3     0.658780 -0.958319  1.361958  1.604140  0.275303  
4     0.639243  1.676895  0.695660  1.137504 -1.312575  
...        ...       ...       ...       ...       ...  
7995  0.572703 -1.209413  0.313976 -1.625728 -0.637401  
7996 -1.048148 -1.094647 -0.755209  0.734821 -0.304433  
7997 -1.046683  1.253539  0.293100 -1.550587  0.810344  
7998  0.018984 -0.182448 -0.388255 -0.726781  1.667916  
7999 -1.513302  1.230438 -1.174110  1.179282  0.783627  

[8000 rows x 12 columns]

In [10]:
x_test_transformed = scaler.transform(x_test)

x_test_transformed = pd.DataFrame(x_test_transformed,columns = x_test.columns)

x_test_transformed

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.593951 -0.412733  1.503924  1.116943  0.403423 -1.492971 -0.785033   
1     0.202190  0.374416 -0.188800 -0.522268 -0.225967 -1.058483  0.420047   
2    -1.079044 -0.313745 -0.884634  0.017080 -0.943122  0.112653  0.801335   
3    -0.083120 -1.107327  0.372805 -1.708152  0.753990 -1.637972  0.403805   
4     0.873921  1.438466  0.086662  1.715037 -0.153880 -0.007015 -0.197053   
...        ...       ...       ...       ...       ...       ...       ...   
1995  1.119679 -0.675220 -1.382912  1.287865  0.249565 -0.803325  0.734497   
1996 -1.077913 -0.808691  1.033449  0.337636 -0.166587  0.340913  0.988085   
1997  0.947825 -1.663727 -1.653920  0.532665 -1.518329  1.590144  0.091613   
1998 -1.120235  0.193979 -0.237805  0.421570 -1.162671  0.738702  0.027367   
1999 -1.377640  1.511867  0.282651  1.510837  0.648241 -1.486786 -0.781586   

            p4        g1        g2        g3        g4  
0     1.566781 -0.901007  1.167203 -1.507330  1.084726  
1     1.028627 -1.625721 -0.395660  1.414651  1.226011  
2     0.733004  1.457108 -1.438495  0.651821 -1.682168  
3    -0.088036  0.083322 -1.672322 -0.357714  1.055865  
4     0.472315  0.136549 -1.469731  0.956396 -0.819727  
...        ...       ...       ...       ...       ...  
1995 -0.369263  0.485786 -0.115528 -1.264683 -1.283117  
1996 -1.035753  0.952386  0.892766 -1.062502 -1.094114  
1997  0.974455 -1.233963  0.126391  0.573445  1.319350  
1998  1.265833  1.524336  0.794087 -1.362323 -0.801971  
1999  1.130007  0.493337 -0.917497  0.002950  1.189023  

[2000 rows x 12 columns]

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

rf = RandomForestClassifier(random_state = 1)
etc = ExtraTreesClassifier(random_state = 1)

rf.fit(x_train_transformed, y_train)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [12]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix,classification_report

rf_predictions = rf.predict(x_test_transformed)

cnf_mat = confusion_matrix(y_true=y_test, y_pred=rf_predictions, labels=[ 'stable' , 'unstable' ])

cnf_mat

print(accuracy_score(y_test, rf_predictions))

0.8905


In [13]:
etc.fit(x_train_transformed, y_train)

et_predictions = etc.predict(x_test_transformed)

C:\Users\USER\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [14]:
cnf_mat = confusion_matrix(y_true=y_test, y_pred=et_predictions, labels=[ 'stable' , 'unstable' ])

cnf_mat

array([[ 613,   99],
       [ 118, 1170]], dtype=int64)

In [15]:
imp = etc.feature_importances_

imp

array([0.11917257, 0.11846717, 0.10877427, 0.11498868, 0.04121199,
       0.03890201, 0.04128051, 0.0417289 , 0.0886519 , 0.09533512,
       0.09713771, 0.09434916])

In [16]:
#pip install xgboost

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\USER\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [17]:
#pip install lightgbm


Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\USER\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [18]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state= 1)
xgb.fit(x_train_transformed, y_train)
xg_predictions = xgb.predict(x_test_transformed)



cnf_mat = confusion_matrix(y_true=y_test, y_pred=xg_predictions, labels=[ 'stable' , 'unstable' ])

cnf_mat

array([[ 648,   64],
       [  45, 1243]], dtype=int64)

In [19]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=1)
lgb.fit(x_train_transformed, y_train)
lg_predictions = lgb.predict(x_test_transformed)


cnf_mat = confusion_matrix(y_true=y_test, y_pred=lg_predictions, labels=[ 'stable' , 'unstable' ])

cnf_mat

array([[ 635,   77],
       [  48, 1240]], dtype=int64)

In [23]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None] 

hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

randomizedsearch = RandomizedSearchCV(etc, hyperparameter_grid,cv =5, n_iter= 10, scoring = 'accuracy',n_jobs = -1, verbose = -1,random_state = 1)

best_model_random = randomizedsearch.fit(x_train_transformed, y_train)
print(best_model_random.best_estimator_)
best_model_random.best_score_


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   51.6s finished


ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features=None, max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=8, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=1000,
                     n_jobs=None, oob_score=False, random_state=1, verbose=0,
                     warm_start=False)


0.9245